(defcustom addon-hippie
  nil
  "Enable hippie expand features"
  :type 'boolean
  :group 'features)

(when addon-hippie
  (try-require 'hippie-exp))

(after 'hippie-exp
  (defun my-hippie-expand-completions (&optional hippie-expand-function)
    "Return the full list of possible completions generated by `hippie-expand'.
The optional argument can be generated with `make-hippie-expand-function'."
    (let ((this-command 'my-hippie-expand-completions)
          (last-command last-command)
          (buffer-modified (buffer-modified-p))
          (hippie-expand-function (or hippie-expand-function 'hippie-expand)))
      (cl-flet ((ding)) ; avoid the (ding) when hippie-expand exhausts its options.
        (while (progn
                 (funcall hippie-expand-function nil)
                 (setq last-command 'my-hippie-expand-completions)
                 (not (equal he-num -1)))))))
  
  (defmacro my-ido-hippie-expand-with (hippie-expand-function)
    "Generate an interactively-callable function that offers ido-based completion
using the specified hippie-expand function."
    `(call-interactively
      (lambda (&optional selection)
        (interactive
         (let ((options (my-hippie-expand-completions ,hippie-expand-function)))
           (if options
               (list (ido-completing-read "Completions: " options)))))
        (if selection
            (he-substitute-string selection t)
          (message "No expansion found")))))
  
  (defun my-ido-hippie-expand ()
    "Offer ido-based completion for the word at point."
    (interactive)
    (my-ido-hippie-expand-with 'hippie-expand))
  
  (global-set-key (kbd "C-c /") 'my-ido-hippie-expand)
  
  (defun my-ido-hippie-expand-filename ()
    "Offer ido-based completion for the filename at point."
    (interactive)
    (my-ido-hippie-expand-with
     (make-hippie-expand-function '(try-complete-file-name))))
  
  (global-set-key (kbd "C-c C-f") 'my-ido-hippie-expand-filename)

  (global-set-key (kbd "C-c .") 'hippie-expand-no-case-fold)
  (global-set-key (kbd "C-c ;") 'hippie-expand-lines)
  (global-set-key (kbd "C-c ,") 'completion-at-point))

