(defvar config-dir (expand-file-name "conf" load-emacs-dir)
  "The directory with configuration files")
(defvar theme-dir (expand-file-name "themes" load-emacs-dir)
  "The directory to store custom themes")
(defvar elpa-dir (expand-file-name "elpa" load-emacs-dir)
  "The directory to store packages downloaded from elpa.")
(defvar addons-dir (expand-file-name "add-ons" load-emacs-dir)
  "The directory with extensible functionality to toggle on and off.")
(defvar backup-dir (expand-file-name "backup" load-emacs-dir)
  "The directory to store backups and autosaves")
(defvar vendor-dir (expand-file-name "vendor" load-emacs-dir)
  "The directory where 3rd party elisp code is stored")
(defvar shared-dir (expand-file-name "shared" load-emacs-dir)
  "The directory that is persistent between machines")

;; Define the names of the variable files
(defvar defaults-file (expand-file-name "defaults.el" load-emacs-dir)
  "The file containing primary variable definitions")
(defvar local-defaults-file (expand-file-name "local.el" load-emacs-dir)
  "The file containing primary variable definitions for the local machine")
(defvar encrypted-variables-file (expand-file-name ".secrets.el.gpg" load-emacs-dir)
  "The file containing sensitive information such as passwords")

(defvar fg/default-theme nil
  "Default theme to load at startup. If nil load a random theme that isn't blacklisted.")

(defvar fg/theme-mode-package-alist '((afternoon . afternoon-theme)
				      (ample . ample-theme)
				      (ample-zen . ample-zen-theme)
				      (anti-zenburn . anti-zenburn-theme)
				      (badger . badger-theme)
				      (base16-chalk . base16-theme)
				      (base16-default . base16-theme)
				      (base16-eighties . base16-theme)
				      (base16-greenscreen . base16-theme)
				      (base16-mocha . base16-theme)
				      (base16-monokai . base16-theme)
				      (base16-ocean . base16-theme)
				      (base16-railscasts . base16-theme)
				      (base16-solarized . base16-theme)
				      (base16-tomorrow . base16-theme)
				      (basic . basic-theme)
				      (birds-of-paradise-plus . birds-of-paradise-plus-theme)
				      (bliss . bliss-theme)
				      (boron . boron-theme)
				      (brin . sublime-themes)
				      (bubbleberry . bubbleberry-theme)
				      (busybee . busybee-theme)
				      (calmer-forest . calmer-forest-theme)
				      (cherry-blossom . cherry-blossom-theme)
				      (clues . clues-theme)
				      (colonoscopy . colonoscopy-theme)
				      (cyberpunk . cyberpunk-theme)
				      (dakrone . dakrone-theme)
				      (dark-krystal . dark-krystal-theme)
				      (darkmine . darkmine-theme)
				      (distinguished . distinguished-theme)
				      (django . django-theme)
				      (dorsey . sublime-themes)
				      (espresso . espresso-theme)
				      (firebelly . firebelly-theme)
				      (firecode . firecode-theme)
				      (flatland-black . flatland-black-theme)
				      (flatland . flatland-theme)
				      (flatui . flatui-theme)
				      (fogus . sublime-themes)
				      (gandalf . gandalf-theme)
				      (gotham . gotham-theme)
				      (graham . sublime-themes)
				      (granger . sublime-themes)
				      (grandshell . grandshell-theme)
				      (gruber-darker . gruber-darker-theme)
				      (gruvbox . gruvbox-theme)
				      (hc-zenburn . hc-zenburn-theme)
				      (heroku . heroku-theme)
				      (hickey . sublime-themes)
				      (hipster . hipster-theme)
				      (inkpot . inkpot-theme)
				      (ir-black . ir-black-theme)
				      (jazz . jazz-theme)
				      (junio . sublime-themes)
				      (leuven . leuven-theme)
				      (light-soap . light-soap-theme)
				      (lush . lush-theme)
				      (mbo70s . mbo70s-theme)
				      (mccarthy . sublime-themes)
				      (mellow . mellow-theme)
				      (minimal . minimal-theme)
				      (molokai . molokai-theme)
				      (monochrome . monochrome-theme)
				      (monokai . monokai-theme)
				      (mustang . mustang-theme)
				      (mustard . mustard-theme)
				      (naquadah . naquadah-theme)
				      (niflheim . niflheim-theme)
				      (noctilux . noctilux-theme)
				      (obsidian . obsidian-theme)
				      (occidental . occidental-theme)
				      (odersky . sublime-themes)
				      (oldlace . oldlace-theme)
				      (organic-green . organic-green-theme)
				      (pastels-on-dark . pastels-on-dark-theme)
				      (peacock . peacock-theme)
				      (phoenix-dark-mono . phoenix-dark-mono-theme)
				      (phoenix-dark-pink . phoenix-dark-pink-theme)
				      (planet . planet-theme)
				      (professional . professional-theme)
				      (purple-haze . purple-haze-theme)
				      (reverse . reverse-theme)
				      (ritchie . sublime-themes)
				      (seti . seti-theme)
				      (slime . slime-theme)
				      (smyx . smyx-theme)
				      (soft-charcoal . soft-charcoal-theme)
				      (soft-morning . soft-morning-theme)
				      (soft-stone . soft-stone-theme)
				      (solarized-dark . solarized-theme)
				      (solarized-light . solarized-theme)
				      (soothe . soothe-theme)
				      (spacegray . spacegray-theme)
				      (spolsky . sublime-themes)
				      (stekene-light . stekene-theme)
				      (stekene-dark . stekene-theme)
				      (subatomic . subatomic-theme)
				      (subatomic256 . subatomic256-theme)
				      (sunny-day . sunny-day-theme)
				      (tango-2 . tango-2-theme)
				      (tango-plus . tango-plus-theme)
				      (tangotango . tangotango-theme)
				      (wilson . sublime-themes)
				      (zenburn . zenburn-theme))
  "Association list of (theme-name . theme-package) cons cells")

(defvar fg/blacklisted-themes-list '()
  "Themes that should not be loaded for various reasons.")

(provide 'fg-config)
