(defvar config-dir (expand-file-name "conf" load-emacs-dir)
  "The directory with configuration files")
(defvar theme-dir (expand-file-name "themes" load-emacs-dir)
  "The directory to store custom themes")
(defvar elpa-dir (expand-file-name "elpa" load-emacs-dir)
  "The directory to store packages downloaded from elpa.")
(defvar addons-dir (expand-file-name "add-ons" load-emacs-dir)
  "The directory with extensible functionality to toggle on and off.")
(defvar backup-dir (expand-file-name "backup" load-emacs-dir)
  "The directory to store backups and autosaves")
(defvar vendor-dir (expand-file-name "vendor" load-emacs-dir)
  "The directory where 3rd party elisp code is stored")
(defvar shared-dir (expand-file-name "shared" load-emacs-dir)
  "The directory that is persistent between machines")

;; Define the names of the variable files
(defvar defaults-file (expand-file-name "defaults.el" load-emacs-dir)
  "The file containing primary variable definitions")
(defvar local-defaults-file (expand-file-name "local.el" load-emacs-dir)
  "The file containing primary variable definitions for the local machine")
(defvar encrypted-variables-file (expand-file-name ".secrets.el.gpg" load-emacs-dir)
  "The file containing sensitive information such as passwords")

(provide 'fg-config)
