(message "* --[ Loading encrypted variables ]--")
(if (file-exists-p encrypted-variables-file)
    (load encrypted-variables-file)
  (message "No secrets found at path: %s" encrypted-variables-file))
(provide 'fg-secrets)
